In [1]:
import pandas as pd
import numpy as np
pd.options.display.max_columns = None

In [2]:
df = pd.read_csv("food-allergy-analysis-Zenodo.csv")
df

SUBJECT_ID  BIRTH_YEAR GENDER_FACTOR   RACE_FACTOR   ETHNICITY_FACTOR  \
0                1        2006   S1 - Female    R1 - Black  E0 - Non-Hispanic   
1                2        1994   S1 - Female    R0 - White  E0 - Non-Hispanic   
2                3        2006     S0 - Male    R0 - White      E1 - Hispanic   
3                4        2004     S0 - Male  R4 - Unknown      E1 - Hispanic   
4                5        2006   S1 - Female    R1 - Black  E0 - Non-Hispanic   
...            ...         ...           ...           ...                ...   
333195      333196        2006     S0 - Male    R0 - White  E0 - Non-Hispanic   
333196      333197        2006   S1 - Female    R1 - Black  E0 - Non-Hispanic   
333197      333198        2006     S0 - Male    R0 - White  E0 - Non-Hispanic   
333198      333199        2006     S0 - Male    R3 - Other  E0 - Non-Hispanic   
333199      333200        2006   S1 - Female    R0 - White  E0 - Non-Hispanic   

             PAYER_FACTOR  ATOPIC_MARCH_COHORT  AGE_START_YEARS  \
0           P1 - Medicaid                False         0.093087   
1       P0 - Non-Medicaid                False        12.232717   
2       P0 - Non-Medicaid                 True         0.010951   
3       P0 - Non-Medicaid                False         2.398357   
4       P0 - Non-Medicaid                False         0.013689   
...                   ...                  ...              ...   
333195  P0 - Non-Medicaid                False         0.736482   
333196      P1 - Medicaid                 True         0.019165   
333197  P0 - Non-Medicaid                False         0.443532   
333198  P0 - Non-Medicaid                 True         0.013689   
333199  P0 - Non-Medicaid                False         0.019165   

        AGE_END_YEARS  SHELLFISH_ALG_START  SHELLFISH_ALG_END  FISH_ALG_START  \
0            3.164956                  NaN                NaN             NaN   
1           18.880219                  NaN                NaN             NaN   
2            6.726899                  NaN                NaN             NaN   
3            9.111567                  NaN                NaN             NaN   
4            6.193018                  NaN                NaN             NaN   
...               ...                  ...                ...             ...   
333195       7.449692                  NaN                NaN             NaN   
333196       6.984257                  NaN                NaN             NaN   
333197       7.405886                  NaN                NaN             NaN   
333198       7.017112                  NaN                NaN             NaN   
333199       3.014374                  NaN                NaN             NaN   

        FISH_ALG_END  MILK_ALG_START  MILK_ALG_END  SOY_ALG_START  \
0                NaN             NaN           NaN            NaN   
1                NaN             NaN           NaN            NaN   
2                NaN        1.002053      1.002053            NaN   
3                NaN             NaN           NaN            NaN   
4                NaN             NaN           NaN            NaN   
...              ...             ...           ...            ...   
333195           NaN             NaN           NaN            NaN   
333196           NaN             NaN           NaN            NaN   
333197           NaN             NaN           NaN            NaN   
333198           NaN             NaN           NaN            NaN   
333199           NaN             NaN           NaN            NaN   

        SOY_ALG_END  EGG_ALG_START  EGG_ALG_END  WHEAT_ALG_START  \
0               NaN            NaN          NaN              NaN   
1               NaN            NaN          NaN              NaN   
2               NaN            NaN          NaN              NaN   
3               NaN            NaN          NaN              NaN   
4               NaN            NaN          NaN              NaN   
...             ... 

In [3]:
df.ASTHMA_START.isnull().sum()

269326

In [4]:
(df.ASTHMA_START.isnull().sum())/(len(df))

0.8083013205282112

In [5]:
df[["SUBJECT_ID", "BIRTH_YEAR", "GENDER_FACTOR","RACE_FACTOR","ETHNICITY_FACTOR"]]

SUBJECT_ID  BIRTH_YEAR GENDER_FACTOR   RACE_FACTOR   ETHNICITY_FACTOR
0                1        2006   S1 - Female    R1 - Black  E0 - Non-Hispanic
1                2        1994   S1 - Female    R0 - White  E0 - Non-Hispanic
2                3        2006     S0 - Male    R0 - White      E1 - Hispanic
3                4        2004     S0 - Male  R4 - Unknown      E1 - Hispanic
4                5        2006   S1 - Female    R1 - Black  E0 - Non-Hispanic
...            ...         ...           ...           ...                ...
333195      333196        2006     S0 - Male    R0 - White  E0 - Non-Hispanic
333196      333197        2006   S1 - Female    R1 - Black  E0 - Non-Hispanic
333197      333198        2006     S0 - Male    R0 - White  E0 - Non-Hispanic
333198      333199        2006     S0 - Male    R3 - Other  E0 - Non-Hispanic
333199      333200        2006   S1 - Female    R0 - White  E0 - Non-Hispanic

[333200 rows x 5 columns]

In [6]:
333200 - 331108

2092

In [7]:
df["PAYER_FACTOR"].value_counts()

P0 - Non-Medicaid    246340
P1 - Medicaid         86860
Name: PAYER_FACTOR, dtype: int64

In [8]:
#target = []
#for rows in df["ASTHMA_START"]:
   # if rows > 

In [9]:
df["ASTHMA_START"].fillna(0, inplace = True)
df.ASTHMA_START.value_counts()

0.000000     269326
1.002053       5274
2.004107         57
1.004791         55
2.009582         52
              ...  
15.452430         1
16.125941         1
17.930185         1
22.009582         1
20.334018         1
Name: ASTHMA_START, Length: 6172, dtype: int64

In [10]:
target = []
for rows in df["ASTHMA_START"]:
    if rows > 0:
        target.append(1)
    else:
        target.append(0)

In [11]:
df["target"] = target

In [12]:
df.target.value_counts()

0    269326
1     63874
Name: target, dtype: int64

# Asthma prediction base on given condition -> predict base on a person's given information

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 333200 entries, 0 to 333199
Data columns (total 51 columns):
 #   Column                   Non-Null Count   Dtype  
---  ------                   --------------   -----  
 0   SUBJECT_ID               333200 non-null  int64  
 1   BIRTH_YEAR               333200 non-null  int64  
 2   GENDER_FACTOR            333200 non-null  object 
 3   RACE_FACTOR              333200 non-null  object 
 4   ETHNICITY_FACTOR         333200 non-null  object 
 5   PAYER_FACTOR             333200 non-null  object 
 6   ATOPIC_MARCH_COHORT      333200 non-null  bool   
 7   AGE_START_YEARS          333200 non-null  float64
 8   AGE_END_YEARS            333200 non-null  float64
 9   SHELLFISH_ALG_START      5246 non-null    float64
 10  SHELLFISH_ALG_END        1051 non-null    float64
 11  FISH_ALG_START           1796 non-null    float64
 12  FISH_ALG_END             527 non-null     float64
 13  MILK_ALG_START           7289 non-null    float64
 14  MILK

In [15]:
X = df[["BIRTH_YEAR", "GENDER_FACTOR","RACE_FACTOR","ETHNICITY_FACTOR","PAYER_FACTOR","ATOPIC_MARCH_COHORT"]]
X

BIRTH_YEAR GENDER_FACTOR   RACE_FACTOR   ETHNICITY_FACTOR  \
0             2006   S1 - Female    R1 - Black  E0 - Non-Hispanic   
1             1994   S1 - Female    R0 - White  E0 - Non-Hispanic   
2             2006     S0 - Male    R0 - White      E1 - Hispanic   
3             2004     S0 - Male  R4 - Unknown      E1 - Hispanic   
4             2006   S1 - Female    R1 - Black  E0 - Non-Hispanic   
...            ...           ...           ...                ...   
333195        2006     S0 - Male    R0 - White  E0 - Non-Hispanic   
333196        2006   S1 - Female    R1 - Black  E0 - Non-Hispanic   
333197        2006     S0 - Male    R0 - White  E0 - Non-Hispanic   
333198        2006     S0 - Male    R3 - Other  E0 - Non-Hispanic   
333199        2006   S1 - Female    R0 - White  E0 - Non-Hispanic   

             PAYER_FACTOR  ATOPIC_MARCH_COHORT  
0           P1 - Medicaid                False  
1       P0 - Non-Medicaid                False  
2       P0 - Non-Medicaid                 True  
3       P0 - Non-Medicaid                False  
4       P0 - Non-Medicaid                False  
...                   ...                  ...  
333195  P0 - Non-Medicaid                False  
333196      P1 - Medicaid                 True  
333197  P0 - Non-Medicaid                False  
333198  P0 - Non-Medicaid                 True  
333199  P0 - Non-Medicaid                False  

[333200 rows x 6 columns]

In [16]:
target1 = []
for rows in X["ATOPIC_MARCH_COHORT"]:
    if rows == True:
        target1.append(1)
    else:
        target1.append(0)

In [17]:
X["ATOPIC_MARCH_COHORT_1"] = target1
X

C:\Users\Jason Yang\AppData\Local\Temp\ipykernel_12396\3759284913.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X["ATOPIC_MARCH_COHORT_1"] = target1


BIRTH_YEAR GENDER_FACTOR   RACE_FACTOR   ETHNICITY_FACTOR  \
0             2006   S1 - Female    R1 - Black  E0 - Non-Hispanic   
1             1994   S1 - Female    R0 - White  E0 - Non-Hispanic   
2             2006     S0 - Male    R0 - White      E1 - Hispanic   
3             2004     S0 - Male  R4 - Unknown      E1 - Hispanic   
4             2006   S1 - Female    R1 - Black  E0 - Non-Hispanic   
...            ...           ...           ...                ...   
333195        2006     S0 - Male    R0 - White  E0 - Non-Hispanic   
333196        2006   S1 - Female    R1 - Black  E0 - Non-Hispanic   
333197        2006     S0 - Male    R0 - White  E0 - Non-Hispanic   
333198        2006     S0 - Male    R3 - Other  E0 - Non-Hispanic   
333199        2006   S1 - Female    R0 - White  E0 - Non-Hispanic   

             PAYER_FACTOR  ATOPIC_MARCH_COHORT  ATOPIC_MARCH_COHORT_1  
0           P1 - Medicaid                False                      0  
1       P0 - Non-Medicaid                False                      0  
2       P0 - Non-Medicaid                 True                      1  
3       P0 - Non-Medicaid                False                      0  
4       P0 - Non-Medicaid                False                      0  
...                   ...                  ...                    ...  
333195  P0 - Non-Medicaid                False                      0  
333196      P1 - Medicaid                 True                      1  
333197  P0 - Non-Medicaid                False                      0  
333198  P0 - Non-Medicaid                 True                      1  
333199  P0 - Non-Medicaid                False                      0  

[333200 rows x 7 columns]

In [18]:
X.drop('ATOPIC_MARCH_COHORT',
  axis='columns', inplace=True)
X

C:\Users\Jason Yang\AppData\Local\Temp\ipykernel_12396\3432281895.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X.drop('ATOPIC_MARCH_COHORT',


BIRTH_YEAR GENDER_FACTOR   RACE_FACTOR   ETHNICITY_FACTOR  \
0             2006   S1 - Female    R1 - Black  E0 - Non-Hispanic   
1             1994   S1 - Female    R0 - White  E0 - Non-Hispanic   
2             2006     S0 - Male    R0 - White      E1 - Hispanic   
3             2004     S0 - Male  R4 - Unknown      E1 - Hispanic   
4             2006   S1 - Female    R1 - Black  E0 - Non-Hispanic   
...            ...           ...           ...                ...   
333195        2006     S0 - Male    R0 - White  E0 - Non-Hispanic   
333196        2006   S1 - Female    R1 - Black  E0 - Non-Hispanic   
333197        2006     S0 - Male    R0 - White  E0 - Non-Hispanic   
333198        2006     S0 - Male    R3 - Other  E0 - Non-Hispanic   
333199        2006   S1 - Female    R0 - White  E0 - Non-Hispanic   

             PAYER_FACTOR  ATOPIC_MARCH_COHORT_1  
0           P1 - Medicaid                      0  
1       P0 - Non-Medicaid                      0  
2       P0 - Non-Medicaid                      1  
3       P0 - Non-Medicaid                      0  
4       P0 - Non-Medicaid                      0  
...                   ...                    ...  
333195  P0 - Non-Medicaid                      0  
333196      P1 - Medicaid                      1  
333197  P0 - Non-Medicaid                      0  
333198  P0 - Non-Medicaid                      1  
333199  P0 - Non-Medicaid                      0  

[333200 rows x 6 columns]

In [19]:
Y = df["target"]
Y.value_counts()

0    269326
1     63874
Name: target, dtype: int64

In [20]:
X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size = 0.2)

In [21]:
from sklearn.ensemble import RandomForestRegressor

In [22]:
model = RandomForestRegressor()
model.fit(X_train, y_train)
model.score(X_test,y_test)

ValueError: could not convert string to float: 'S1 - Female'

In [23]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer


In [24]:
categorical_features = ["GENDER_FACTOR","RACE_FACTOR","ETHNICITY_FACTOR","PAYER_FACTOR"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot",one_hot,categorical_features)],remainder = "passthrough")
transformer

ColumnTransformer(remainder='passthrough',
                  transformers=[('one_hot', OneHotEncoder(),
                                 ['GENDER_FACTOR', 'RACE_FACTOR',
                                  'ETHNICITY_FACTOR', 'PAYER_FACTOR'])])

In [25]:
# Assuming df is your DataFrame
shape = X

# Check the dimensions
if len(shape) == 1:
    print("DataFrame is 1D array")
elif len(shape) == 2:
    print("DataFrame is 2D array")
else:
    print("DataFrame has more than 2 dimensions")

DataFrame has more than 2 dimensions


In [26]:
X_intoTransform = X[["GENDER_FACTOR","RACE_FACTOR","ETHNICITY_FACTOR","PAYER_FACTOR"]]
X_intoTransform.isnull().any()

GENDER_FACTOR       False
RACE_FACTOR         False
ETHNICITY_FACTOR    False
PAYER_FACTOR        False
dtype: bool

In [27]:
transform_Xdata = transformer.fit_transform(X_intoTransform)

In [28]:
transform_Xdata

array([[0., 1., 0., ..., 0., 0., 1.],
       [0., 1., 1., ..., 0., 1., 0.],
       [1., 0., 1., ..., 1., 1., 0.],
       ...,
       [1., 0., 1., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 1., 0.]])

In [29]:
pd.DataFrame(transform_Xdata)

0    1    2    3    4    5    6    7    8    9    10
0       0.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0
1       0.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0
2       1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0
3       1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  1.0  0.0
4       0.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
333195  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0
333196  0.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0
333197  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0
333198  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0
333199  0.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0

[333200 rows x 11 columns]

In [30]:
X_train,X_test,y_train,y_test = train_test_split(transform_Xdata,Y,test_size = 0.2)

In [31]:
model.fit(X_train,y_train)

RandomForestRegressor()

In [32]:
model.score(X_test,y_test)

0.01881924901639953

## Try using different model

In [33]:
from sklearn.linear_model import Ridge 

In [34]:
model1 = Ridge()

In [35]:
model1.fit(X_train,y_train)

Ridge()

In [36]:
model1.score(X_test,y_test)

0.018383907209315598

## so the linear model is actully worse than the random model

# Now use random forrest model to see if its any better

In [37]:
from sklearn.ensemble import RandomForestRegressor

In [38]:
np.random.seed(42)

In [39]:
model2 = RandomForestRegressor()

In [40]:
model2.fit(X_train,y_train)

RandomForestRegressor()

In [41]:
model2.score(X_test,y_test)

0.018834956872001873

## Conclusion -> the data is not so good

In [42]:
X_test

array([[1., 0., 1., ..., 0., 1., 0.],
       [1., 0., 1., ..., 1., 1., 0.],
       [1., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 1., 0., ..., 0., 0., 1.],
       [1., 0., 1., ..., 0., 1., 0.],
       [1., 0., 1., ..., 0., 1., 0.]])

In [43]:
model2.predict(X_test)

array([0.1901232 , 0.217344  , 0.30273263, ..., 0.232426  , 0.1901232 ,
       0.1901232 ])

In [44]:
np.array(y_test)

array([0, 1, 1, ..., 0, 0, 0], dtype=int64)

In [45]:
y_preds = model2.predict(X_test)
np.mean(y_preds == y_test)

1.5006002400960385e-05